"""AUTO-GENERATED by the Thinking Machine agent. Do not hand-edit -
it is overwritten every time an idea is parsed or an improvement is applied.

Strategy: 'sweep_reversion_emaFilter' | LONG when [sweep_low + price_above_ema] | SHORT when [sweep_high + price_below_ema] | stop=1.0xATR, target=1.5R | window=09:30..close | max 1/day
"""
from core.strategy import StrategySpec

SPEC = StrategySpec(
    name='sweep_reversion_emaFilter',
    long_entry=['sweep_low', 'price_above_ema'],
    short_entry=['sweep_high', 'price_below_ema'],
    ema_period=20,
    atr_period=14,
    sweep_lookback=20,
    stop_atr=1.0,
    rr=1.5,
    rth_only=True,
    entry_after='09:30',
    entry_before=None,
    max_trades_per_day=1,
    exit_on_session_close=True,
)
